exports.DEFAULT_ENDPOINT = 'http://localhost:9191/api'
exports.DEFAULT_COLLECTION = 'default'
exports.SCHEMA_RESOURCE = 'sonar/resource'
exports.METADATA_ID = 'sonar.id'
exports.HYPERDRIVE_SCHEME = 'dat:'
